**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Lab 3: Numbers, Expressions and Functions**                             

## Fill up the following declaration details:
**I certify that this report is my own work, based on my personal study and/or research. I also certify that this report has not previously been submitted for assessment in any other unit, and that I have not copied in part or whole or otherwise plagiarised the work of other students and/or persons.**
- Name:
- Matrix Number: 
- Date: 


## General Instruction:
Let say your matrix number is S54321. For computation below, ignore the first letter and use your matrix number by letting $\mathbf{(\alpha , \beta, \gamma, \kappa, \lambda) =(5,4,3,2,1)}$. Hence replace explicitly the values of greek letters as $\alpha = 5, \beta = 4, \gamma = 3, \kappa = 2, \lambda =1$.


For example:

**Q0.** Compute $(\beta * \gamma * \kappa)+{\lambda})$:

In [1]:
(4*3*2)+1

25

## Name your file as follows before submiting via pembelajaran.umt.edu.my
- save as **matrixnumber-labnumber.ipynb**: for example **S54321-LAB4.ipynb**

# LAB (4) QUESTIONS

**Q0.**  Import NumPy module below as np and print out the version you're running:

In [2]:
import numpy as np
np.__version__

'1.20.2'

## PART A: VECTORS

**Q1.**  A **vector** in ${\mathbb{R}}^n$ is an $n$-tuple, or point, in ${\mathbb{R}}^n$ can be represented in a row or column vector. Create a vector in ${\mathbb{R}}^4$ as follows:
- Create a  **row vector** and store is as $v_1 = (\alpha , \beta, \gamma, \kappa )$, 
- Create a **column vector** and store is as $v_2 =(\beta, \gamma, \kappa \lambda )$, . 

(1, 4)
(4, 1)


**Q2.** The **norm** of a vector is a measure of its length is denoted as $\Vert v \Vert_{2}$ =$ \sqrt{\sum_i v_i^2}$. Find the norm of $v_2$.

**TIPS:** use`linalg.norm()` function.

L2 norm :  5.477225575051661


**Q3.** First, Transpose $v_1$ and store it as $v_3$. Next, vector addition: $v_4 = v_2 + v_3$

**TIPS:** use`.T`  or `transpose()` function.

[[5]
 [4]
 [3]
 [2]]
v2+v3: [[9]
 [7]
 [5]
 [3]]


**Q4.** Find the scalar product: $\beta(v_2 + v_3)$


scalar product:  [[36]
 [28]
 [20]
 [12]]


**Q5.** The **angle between two vectors**, $\theta$, is defined by the formula:
$$
v \cdot w = \Vert v \Vert_{2} \Vert w \Vert_{2} \cos{\theta}
$$
 Compute the angle between the vectors $v_2$ and $v_4$. 
 
 **TIPS:** use`linalg.norm`,`arccos()` and `dot` function.

[[4]
 [3]
 [2]
 [1]]
[[5]
 [4]
 [3]
 [2]]
[[0.11134101]]


**Q6.** The **cross product** between two vectors, $v$ and $w$, is written $v \times w$. The geometric interpretation of the cross product is a vector perpendicular to both $v$ and $w$ with length equal to the area enclosed by the parallelogram created by the two vectors.

Given the vectors $v = [0, \beta, 0]$ and $w = [\kappa, 0, 0]$, use the Numpy function cross to compute the cross product of v and w.

[[  0   0 -12]]


## PART B: MATRIX

**Q7.**  Create matrix A using `ndarray`, by letting the elements in the form of `int64`:

$$
\begin{equation}
	A_{3 \times 3}=\begin{bmatrix}
	  a_{11} & a_{12}  & a_{13} \\
	  a_{21} & a_{22} & a_{23} \\
	  a_{31} & a_{32} & a_{33} 
	\end{bmatrix}
 = \begin{bmatrix}
	  1 & 5 & a_{13} \\
	  2 & 6 & a_{23} \\
	  3 & 7 & a_{33} 
	\end{bmatrix}
\end{equation}
$$

where $$\mathbf{(a_{13}, a_{23},a_{33})=(\alpha , \beta, \gamma)}$$ 


array([[ 0,  0,  5],
       [ 0, -6,  4],
       [ 3, -7,  3]])

**Q8.**  Identify builtin NumPy's function to identify the following property of created matrix A above:

1. row x column
2. number of elements
3. type of the elements
4. number of bytes to store this matrix
5. the dimension of this array

row x column: (3, 3)
number of elements: 9
type of the elements: int32
bytes: 36
dimension: 2


**Q9.** Compute the following based on matrix A

1. Transpose matrix A and save it as marix B
2. Store the last column of matrix B as c3  
3. Store the last row of matrix B as r3
4. What is the enty of element $B_{3,3}$ 
5. Find the dot product of c3 and r3

[[ 0  0  3]
 [ 0 -6 -7]
 [ 5  4  3]]
[ 3 -7  3]
[ 3 -7  3]
B33 =  3
dot product of c3.r3 = -4


 A **square matrix** has the same number of rows as columns. The determinant is denoted as $det(M)$ or $|M|$ , readily available in Numpy's `linalg` package.For example  $2 \times 2$ matrix, the determinant is:
$$
|M| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc$$

If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.

**Q10.** Computer the following:
1. Compute the determinant of matrix A as store is as `ADet`. 
2. Identify if matrix A is singular. Singular matrices has no inverse!
3. Show that the the dot product of `A` and `ADet` equals to an identity matrix

TIPS: use `linalg.det(A)` function to compute


[[ 0  0  5]
 [ 0 -6  4]
 [ 3 -7  3]]
90.0


The **inverse** of a square matrix $M$ is a matrix of the same size, $N$, such that $M \cdot N = I$.  A matrix is said to be **invertible** if it has an inverse. The inverse of a matrix is unique; that is, for an invertible matrix, there is only one inverse for that matrix. If $M$ is a square matrix, its inverse is denoted by $M^{-1}$ in mathematics, and it can be computed in Python using the function *inv* from Numpy's *linalg* package.

For a $2 \times 2$ matrix, the analytic solution of the matrix inverse is:

$$
M^{-1} = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix}^{-1} = \frac{1}{|M|}\begin{bmatrix}
d & -b \\
-c & a\\
\end{bmatrix}$$

**Q11.** 
1. First, find the inverse of A and store is as AInverce 
2. Next, find the dot product of A and its inverse to produce an identity matrix.

**TIPS:** You can only find the inverse if $det(A)\neq 0$

[[ 0.11111111 -0.38888889  0.33333333]
 [ 0.13333333 -0.16666667 -0.        ]
 [ 0.2         0.          0.        ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  8.32667268e-17  1.00000000e+00]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


## PART C: Various types of Dataset

**Q12.** Add a new column to matrix A in as a first column with entries: $\gamma, \kappa, \lambda $ and store as matrix C
**TIPS:** 
- use`hstack` function to add.

array([[ 0,  0,  5,  3],
       [ 0, -6,  4,  2],
       [ 3, -7,  3,  1]])

**Q13.** Convert matrix C as a one dimensional array and store as `samples`. Next compute the following:

**TIPS:** use`flatten` function to convert.

1. compute the biggest number in this list
2. compute the smallest number in this list
3. total sum
4. total product
5. mean
6. standard deviation
7. varians

5
-7
8
0
0.6666666666666666
3.5668224265054502
12.722222222222227


## CSV file

 Load population file by running the following cell:

# year,hare,lynx,carrot
1900,3.00E+04,4.00E+03,48300
1901,4.72E+04,6.10E+03,48200
1902,7.02E+04,9.80E+03,41500
1903,7.74E+04,3.52E+04,38200
1904,3.63E+04,5.94E+04,40600


**Q14** Compute the following:
1. Compute mean for hares, lynxs and carrots

Mean for Hares: 34080.95238095238
Mean for Lynxs: 20166.666666666668
Mean for Carrots: 42400.0


2. Which year each species had the largest population?

Year with largest population hares:  [1903.]
Year with largest population lynxs:  [1904.]
Year with largest population carrots:  [1900.]


3. Which year carrots were lowest and identify the corresponding hares and lynxes that year.

Min Carrots : 36700.0
Year with least population carrots:  [1916.]
Nu of hares that year:  [11200.]
Nu of lynxes that year:  [29700.]
