**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Chapter 3: Lists, Arrays, Vectors and Matrix Operations**   

**PART 1: Previous Notebook**

1. Types of Sequences in Python: Built-in containers

**PART 2**

2. Arrays                   
3. Column and row vector
4. Matrix representation

**PART 3**

5. Introduction to array operations 
6. Vector and Matrix Operations
7. Towards Higher dimensions
8. Reading and writing files
9. Bonus: Python for Data Analysis (Pandas)

**References:** 

- [NumPy](https://numpy.org/)
- Robert Johansson, Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2019, Apress).
>Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9). The source code listings can be downloaded from http://www.apress.com/9781484205549

- VanderPlas, Jacob T,  Python data science handbook: essential tools for working with data, O'Reilly Media, 2017. This book is made available [online](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) 
>The source code listings can be downloaded from [Jake's GitHub] (https://github.com/jakevdp/PythonDataScienceHandbook)

- Travis E. Oliphant(creater of NumPy), [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf)

---
**PART 2**

# Introduction

The heart of SciPy is **NumPy** module. We will be using **NumPy** for this chapter, which is the fundamental package for scientific computing with Python. 
> Paragraphs below are taken from [numpy documentation](https://numpy.org/doc/stable/user/whatisnumpy.html):

## What is NumPy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a **multidimensional array** object, various derived objects (such as masked arrays and matrices), and an assortment of routines for **fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.**

>At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of **homogeneous data types**, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). **Changing the size of an ndarray will create a new array and delete the original.**

2. **The elements in a NumPy array are all required to be of the same data type,** and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

3. NumPy arrays **facilitate advanced mathematical and other types of operations on large numbers of data**. Typically, such operations are executed **more efficiently and with less code** than is possible using Python’s built-in sequences.

4. A growing plethora of scientific and mathematical Python-based packages are **using NumPy arrays**; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, **just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays**.

---

## Why is NumPy Fast?
We can use a `for` loop to repeatedly compute a a set of inputs sequentially, however, this approach consumes time and effort. A better approach is to represent the set of input in the form of vectors, arrays and matrices to carry out operations; this is known as **vectorized computing**

**Vectorization describes the absence of any explicit looping, indexing, etc.,** 
>In the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

1. vectorized code is more **concise and easier** to read

2. fewer lines of code generally means **fewer bugs**

3. the code more closely **resembles standard mathematical notation** (making it easier, typically, to correctly code mathematical constructs)

4. vectorization results in more “Pythonic” code **(easier to read)**. Without vectorization, our code would be littered with inefficient and difficult to read for loops.
---

## Version and loading NumPy

In [2]:
#!pip freeze | (grep 'numpy') # works for linux and Mac

import numpy as np
np.__version__

'1.20.2'

- Installing NumPy

In [48]:
!pip install numpy 

Defaulting to user installation because normal site-packages is not writeable


- Upgrading NumPy

In [49]:
!pip install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeable


In [50]:
import numpy as np
np.__version__

'1.20.2'

- Will will use `np` as NumPy from now onwards

In [51]:
#np. # press <tab> to see available functions

In [52]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Apple\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\__init__.py'>
File:        c:\users\apple\appdata\roaming\python\python38\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three 

-  Find out all the functions are implemented in NumPy module. It returns a sorted list of strings:

In [53]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__

- Query about a function

In [54]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. ve

# Arrays, Row and Column Vectors
See `numpy` [documentation](https://numpy.org/doc/stable/user/quickstart.html)

- builtin list:

In [4]:
list1 = [1, 30, 55]
print(type(list1))
list1

<class 'list'>


[1, 30, 55]

A **vector** in ${\mathbb{R}}^n$ is an $n$-tuple, or point, in ${\mathbb{R}}^n$ can be represented in a row or column vector. 

- We can create an **one dimensional array** from the list above using `array` function which creates ndarray object. 
- Python displays a  **one dimensional** array as `(3,)` and **not as a 1 x 3 matrix**. However, a row vector has the shape of $ 1 \times 3$. 
- basic attributes of ndarray:
> shape, size, ndim, nbytes, dtype

- below is a one dimensional array, Not a row vector!

In [5]:
r1 =  np.array(list1)
print(type(r1))
print(r1.shape)
print(r1.ndim)
print(r1.size) # nu of elements
print(r1.dtype)
print(r1.nbytes)

<class 'numpy.ndarray'>
(3,)
1
3
int64
24


**Two dimensional array** is represented by its shape in the form of **row x column**, which is a nested list.
- Thus, a proper way to represent a **row vector** is in the form of **two dimensional** array using two nested brackets. Example below is a row vector in ${\mathbb{R}}^3$

In [9]:
u = np.array([[5, 4, 3]])
print(u)
print(u.shape)

[[5 4 3]]
(1, 3)


-  we can transpose a row vector to make a **column vector**  of $ 3 \times 1$. Indeed this is a **matrix representation** in the form of **two dimensional array** (visually like a table in excel).

In [12]:
v = u.transpose()
print(u.shape)
print(u.ndim)
print(v)

(1, 3)
2
[[5]
 [4]
 [3]]


-  below is another column vector is a **matrix** of $ 3 \times 1$

In [14]:
w =  np.array([[1], [30], [55], [66]])
print(w.shape)
print(w.ndim)
print(w.size)
print(w)

(4, 1)
2
4
[[ 1]
 [30]
 [55]
 [66]]


**Matrix** is indeed a two dimensional array and it is represented by **row x column**, which is a nested list.
- a $3 \times 4$ matrix as a two dimensional array.
 - NaN represents **not a number**, it is a numeric data type used to represent any value that is undefined or unpresentable. It do not have values and have yet to be computed.

In [59]:
a1 = np.array([['Monday', 2, 3, 4], ['Tuesday', 40, 50, 60], ['Wednesday', 66, 'NaN', 88]])
print(a1.shape)
print(a1.ndim)
print(a1.size)

(3, 4)
2
12


In [60]:
a1

array([['Monday', '2', '3', '4'],
       ['Tuesday', '40', '50', '60'],
       ['Wednesday', '66', 'NaN', '88']], dtype='<U11')

In [61]:
a1.nbytes

528

In [62]:
(a1.size) #number of elements

12

In [63]:
a1.dtype.name # the element's type

'str352'

### Two dimensional elements with various data types

- a simple row vector with elements as strings

In [64]:
a2 = np.array(['a','b'])
a2.dtype.name

'str32'

- various numerical data types

In [65]:
a4 = np.array([1.2, 3.4, 5.6])
a4.dtype.name

'float64'

In [66]:
a5 = np.array([10, 20, 30], dtype=int)
a6 = np.array([10, 20, 30], dtype=float)
a7 = np.array([10, 20, 30], dtype=complex)

In [67]:
a5, a6, a7

(array([10, 20, 30]),
 array([10., 20., 30.]),
 array([10.+0.j, 20.+0.j, 30.+0.j]))

- Data types varies in size: `int32` for 32-bit integers, `int64` for 64-bit integers, etc.

In [68]:
a5.dtype.name, a6.dtype.name, a7.dtype.name

('int32', 'float64', 'complex128')

In [69]:
a5 = np.array([10, 20, 30], dtype = np.int64) # converting to 64 bit 
a5.dtype.name

'int64'

- coverting element's type using `astype`

In [70]:
a8 = np.array([1, 2, 3], dtype=float)
a8

array([1., 2., 3.])

In [71]:
a9 = a8.astype(np.int32) #type casting using astype
a9

array([1, 2, 3])

- promotion due to operation

In [72]:
a10 = np.array([1, 2, 3], dtype=complex)

In [73]:
a11 = a10 + a9
print(a11.dtype)
a11

complex128


array([2.+0.j, 4.+0.j, 6.+0.j])

### Real and imaginary parts

- $\sqrt{-1}$ is undefined in integers, thus proper representation is complex numbers

In [74]:
c0 = np.array([-1, 4, 1])
print(type(c0))
print(c0.dtype.name)
#np.sqrt(c0) # you will not be able to run this

<class 'numpy.ndarray'>
int32


In [75]:
c1 = np.array([-1, 4, 1], dtype=complex)
c2 = np.sqrt(c1)
c2

array([0.+1.j, 2.+0.j, 1.+0.j])

In [76]:
c2.real

array([0., 2., 1.])

In [77]:
c2.imag

array([1., 0., 0.])

In [78]:
c2*c2

array([-1.+0.j,  4.+0.j,  1.+0.j])

# Two dimensional arrays with filled elements

In [79]:
#np.ones?

In [80]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
t1 = np.ones((5,1))
print(t1.dtype)
t1.nbytes
t1

float64


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [82]:
t2 = np.ones((5,1), dtype = np.int32) # integer with different size
print(t2.dtype)
t2.nbytes

int32


20

In [83]:
t3 = 777 * np.ones(10)
t3

array([777., 777., 777., 777., 777., 777., 777., 777., 777., 777.])

- Creating uninitialized arrays

In [84]:
t3s = np.empty(3) # initiated with random values, so must be filled as prefered
t3s

array([0., 0., 0.])

In [85]:
t3s.fill(6.6)
t3s

array([6.6, 6.6, 6.6])

In [86]:
t4 = np.full((1,3), 6.6)
t4

array([[6.6, 6.6, 6.6]])

### Arrays filled with evenly spaced sequences

In [87]:
range(1,5)

range(1, 5)

In [88]:
np.arange(0.0, 3.0, 0.5) #(start, end, stepsize), but without the end node

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [89]:
np.linspace(0, 10, 6) #(start, end,  number of elements), including the end node

array([ 0.,  2.,  4.,  6.,  8., 10.])

### Mesh-grid arrays

In [90]:
x = np.array([-0.1, 0, 0.2])
y = np.array([0, 1, 2])

In [91]:
X, Y = np.meshgrid(x, y)

In [92]:
X #row vector

array([[-0.1,  0. ,  0.2],
       [-0.1,  0. ,  0.2],
       [-0.1,  0. ,  0.2]])

In [93]:
Y # column vector

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

$F(X,Y) = X \times Y$

In [94]:
F = X*Y
F

array([[-0. ,  0. ,  0. ],
       [-0.1,  0. ,  0.2],
       [-0.2,  0. ,  0.4]])

# Creating two dimensional arrays with built-in function

As stated above, **matrix** is indeed a two dimensional array and it is represented by **row x column**, which is a nested list.

In [95]:
np.identity(3) # square Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.eye(3, k=0) # k controls the diagonal 1 entries

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [98]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- creating a diagonal matrix with incremen entries

In [99]:
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [100]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing & Slicing

- choosing an element or a collectin of elements from an array
- similar to lists, index starts at 0.
- last index is -1, second last is -2

- one dimensional array: choosing and slicind similar to list prosedure

In [101]:
a12 = np.arange(0,6)
a12

array([0, 1, 2, 3, 4, 5])

In [102]:
print(a12[0])
print(a12[-1])

0
5


In [103]:
a12[1:3]

array([1, 2])

In [104]:
a12[3:]

array([3, 4, 5])

- matrix: two dimensional array

In [105]:
a13 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10,  11],
       [ 12,  13,  14, 15]])
a13
print(a13.shape)

(4, 4)


- choosing a row

In [106]:
a13[0] # first row

array([0, 1, 2, 3])

In [107]:
a13[0,2]

2

In [108]:
a13[0,:] # another way to choose first row 

array([0, 1, 2, 3])

In [109]:
a13[-1] # last row

array([12, 13, 14, 15])

In [110]:
a13[:] # choose all

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- slicing a number of rows

In [111]:
a12[1:3] # array one and two

array([1, 2])

- choosing a column

In [112]:
a13[:,0] # another way to choose first row 

array([ 0,  4,  8, 12])

In [113]:
a13[:2,:2] # # upper left 2 x 2 submatrices

array([[0, 1],
       [4, 5]])

In [114]:
a13[2:,2:] # # lower right 2 x 2 submatrices

array([[10, 11],
       [14, 15]])

- changing a part 

In [115]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- viewing third row with a new name

In [116]:
a14 = a13[2]
a14

array([ 8,  9, 10, 11])

- giving new value for the chosen row, changes the original entries

In [117]:
a14[:]=0
a14

array([0, 0, 0, 0])

In [118]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

- copying and storing as a new array instead of changing the original array

In [119]:
a15 = a13[1].copy()
a15

array([4, 5, 6, 7])

In [120]:
a15[:] = 1
a15

array([1, 1, 1, 1])

In [121]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

## Resizing Array

In [122]:
a13.shape


(4, 4)

In [123]:
a13
a16 = a13.flatten()
print(a16)
print(a13)
print(a16.shape)

[ 0  1  2  3  4  5  6  7  0  0  0  0 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 0  0  0  0]
 [12 13 14 15]]
(16,)


- reshaping with equal ammount of elements

In [124]:
print(a13.size)
a17 = np.reshape(a13,(8,2))
a17

16


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 0,  0],
       [ 0,  0],
       [12, 13],
       [14, 15]])

In [125]:
a18 = a17.transpose()
print(a18.shape)
a18

(2, 8)


array([[ 0,  2,  4,  6,  0,  0, 12, 14],
       [ 1,  3,  5,  7,  0,  0, 13, 15]])

- adding an extra row

In [126]:
a19 = np.vstack((a18,a18[1]))
a19

array([[ 0,  2,  4,  6,  0,  0, 12, 14],
       [ 1,  3,  5,  7,  0,  0, 13, 15],
       [ 1,  3,  5,  7,  0,  0, 13, 15]])

In [127]:
#np.hstack?
a20 = np.array([[19],[19],[19]])
a20

array([[19],
       [19],
       [19]])

In [128]:
a21 = np.hstack((a19,a20))
a21

array([[ 0,  2,  4,  6,  0,  0, 12, 14, 19],
       [ 1,  3,  5,  7,  0,  0, 13, 15, 19],
       [ 1,  3,  5,  7,  0,  0, 13, 15, 19]])