**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Chapter 3: Lists, Arrays, Vectors and Matrix Operations**   

**PART 1: Previous Notebook**

1. Types of Sequences in Python: Built-in containers

**PART 2**

2. Arrays                   
3. Column and row vector
4. Matrix representation

**PART 3 : Next Notebook**

4. Vector and matrix operation

**References:** 

- [NumPy](https://numpy.org/)
- Robert Johansson, Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2019, Apress).
>Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9). The source code listings can be downloaded from http://www.apress.com/9781484205549

- VanderPlas, Jacob T,  Python data science handbook: essential tools for working with data, O'Reilly Media, 2017. This book is made available [online](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) 
>The source code listings can be downloaded from [Jake's GitHub] (https://github.com/jakevdp/PythonDataScienceHandbook)

- Travis E. Oliphant(creater of NumPy), [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf)

---
**PART 2**

# Introduction

We will be using **NumPy** module for this chapter, which is the fundamental package for scientific computing with Python. 
> Paragraphs below are taken from [numpy documentation](https://numpy.org/doc/stable/user/whatisnumpy.html):

## What is NumPy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a **multidimensional array** object, various derived objects (such as masked arrays and matrices), and an assortment of routines for **fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.**

>At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of **homogeneous data types**, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). **Changing the size of an ndarray will create a new array and delete the original.**

2. **The elements in a NumPy array are all required to be of the same data type,** and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

3. NumPy arrays **facilitate advanced mathematical and other types of operations on large numbers of data**. Typically, such operations are executed **more efficiently and with less code** than is possible using Python’s built-in sequences.

4. A growing plethora of scientific and mathematical Python-based packages are **using NumPy arrays**; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, **just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays**.

---

## Why is NumPy Fast?
We can use a `for` loop to repeatedly compute a a set of inputs sequentially, however, this approach consumes time and effort. A better approach is to represent the set of input in the form of vectors, arrays and matrices to carry out operations; this is known as **vectorized computing**

**Vectorization describes the absence of any explicit looping, indexing, etc.,** 
>In the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

1. vectorized code is more **concise and easier** to read

2. fewer lines of code generally means **fewer bugs**

3. the code more closely **resembles standard mathematical notation** (making it easier, typically, to correctly code mathematical constructs)

4. vectorization results in more “Pythonic” code **(easier to read)**. Without vectorization, our code would be littered with inefficient and difficult to read for loops.
---

## Version and loading NumPy

In [4]:
#!pip freeze | (grep 'numpy') # works for linux and Mac

import numpy as np
np.__version__

'1.20.2'

- Updating /installing NumPy

In [2]:
!pip install numpy --upgrade

     |████████████████████████████████| 16.0 MB 2.5 MB/s eta 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Uninstalling numpy-1.19.4:
      Successfully uninstalled numpy-1.19.4


In [3]:
import numpy as np
np.__version__

'1.20.2'

- Will will use `np` as NumPy from now onwards

In [ ]:
#np.<tab>

In [4]:
#np?

-  Find out all the functions are implemented in NumPy module. It returns a sorted list of strings:

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__

- Query about a function

In [2]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. ve

# Arrays: Column and Row Vectors
See `numpy` [documentation](https://numpy.org/doc/stable/user/quickstart.html)

- builtin list:

In [7]:
list1 = [1, 30, 55]
print(type(list1))
list1

<class 'list'>


[1, 30, 55]

- We can create an **one dimensional array** from the list above using `array` function which creates ndarray object. This is in fact a **row vector**.
- a row vector; $ 1 \times 3$, however it displays as 1-dimensional array and **not as a 1 x n matrix**
- basic attributes of ndarray:
> shape, size, ndim, nbytes, dtype

In [16]:
r1 =  np.array(list1)
print(type(r1))
print(r1.shape)
print(r1.ndim)
print(r1.size)
print(r1.dtype)
print(r1.nbytes)

<class 'numpy.ndarray'>
(3,)
1
3
int64
24


- Matrix is represented by its shape in the form of **row x column**, which is a nested list.
-  we can transpose a row vector to make a **column vector**  of $ 3 \times 1$. Indeed this is a **matrix representation** in the form of **two dimensional array** (visually like a table in excel).

In [152]:
c1 = r1.transpose()
print(c1.shape)
print(c1.ndim)
c1

(3, 1)
2


array([[ 1],
       [30],
       [55]])

-  another column vector is a **matrix** of $ 3 \times 1$

In [17]:
r1 =  np.array([[1], [30], [55], [66]])
print(r1.shape)
print(r1.ndim)
print(r1.size)
r1

(4, 1)
2
4


array([[ 1],
       [30],
       [55],
       [66]])

 - a $3 \times 4$ matrix as a two dimensional array
 - NaN represents **not a number**, it is a numeric data type used to represent any value that is undefined or unpresentable. It do not have values and have yet to be computed.

In [20]:
a1 = np.array([['Monday', 2, 3, 4], ['Tuesday', 40, 50, 60], ['Wednesday', 66, 'NaN', 88]])
print(a1.shape)
print(a1.ndim)
print(a1.size)

(3, 4)
2
12


In [21]:
a1

array([['Monday', '2', '3', '4'],
       ['Tuesday', '40', '50', '60'],
       ['Wednesday', '66', 'NaN', '88']], dtype='<U21')

In [22]:
a1.nbytes

1008

In [23]:
(a1.size) #number of elements

12

In [24]:
a1.dtype.name # the element's type

'str672'

### Elements with various data types

- a simple row vector with elements as strings

In [167]:
a2 = np.array(['a','b'])
a2.dtype.name

'str32'

- various numerical data types

In [168]:
a4 = np.array([1.2, 3.4, 5.6])
a4.dtype.name

'float64'

In [43]:
a5 = np.array([10, 20, 30], dtype=int)
a6 = np.array([10, 20, 30], dtype=float)
a7 = np.array([10, 20, 30], dtype=complex)

In [36]:
a5, a6, a7

(array([10, 20, 30]),
 array([10., 20., 30.]),
 array([10.+0.j, 20.+0.j, 30.+0.j]))

- Data types varies in size: `int32` for 32-bit integers, `int64` for 64-bit integers, etc.

In [44]:
a5.dtype.name, a6.dtype.name, a7.dtype.name

('int64', 'float64', 'complex128')

In [47]:
a5 = np.array([10, 20, 30], dtype = np.int64) # converting to 64 bit 
a5.dtype.name

'int64'

- coverting element's type using `astype`

In [31]:
a8 = np.array([1, 2, 3], dtype=float)
a8

array([1., 2., 3.])

In [36]:
a9 = a8.astype(np.int32) #type casting using astype
a9

array([1, 2, 3], dtype=int32)

- promotion due to operation

In [37]:
a10 = np.array([1, 2, 3], dtype=complex)

In [41]:
a11 = a10 + a9
print(a11.dtype)
a11

complex128


array([2.+0.j, 4.+0.j, 6.+0.j])

### Real and imaginary parts

- $\sqrt{-1}$ is undefined in integers, thus proper representation is complex numbers

In [7]:
c0 = np.array([-1, 4, 1])
print(type(c0))
print(c0.dtype.name)
np.sqrt(c0)

<class 'numpy.ndarray'>
int32


<ipython-input-7-4e19a0f07b7e>:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(c0)


array([nan,  2.,  1.])

In [68]:
c1 = np.array([-1, 4, 1], dtype=complex)
c2 = np.sqrt(c1)
c2

array([0.+1.j, 2.+0.j, 1.+0.j])

In [69]:
c2.real

array([0., 2., 1.])

In [70]:
c2.imag

array([1., 0., 0.])

In [71]:
c2*c2

array([-1.+0.j,  4.+0.j,  1.+0.j])

# Arrays with filled elements

In [69]:
#np.ones?

In [72]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
t1 = np.ones((5,1))
print(t1.dtype)
t1.nbytes

float64


40

In [79]:
t2 = np.ones((5,1), dtype = np.int32) # integer with different size
print(t2.dtype)
t2.nbytes

int32


20

In [95]:
t3 = 777 * np.ones(3)
t3

array([777., 777., 777.])

- Creating uninitialized arrays

In [9]:
t3 = np.empty(3) # initiated with random values, so must be filled as prefered
t3

array([1., 4., 1.])

In [10]:
t3.fill(6.6)
t3

array([6.6, 6.6, 6.6])

In [13]:
    t4 = np.full((1,3), 6.6)
t4

array([[6.6, 6.6, 6.6]])

### Arrays filled with evenly spaced sequences

In [114]:
np.arange(0.0, 3.0, 0.5) #(start, end, stepsize), but without the end node

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [14]:
np.linspace(0, 10, 6) #(start, end,  number of elements), including the end node

array([ 0.,  2.,  4.,  6.,  8., 10.])

### Mesh-grid arrays

In [40]:
x = np.array([-0.1, 0, 0.2])
y = np.array([0, 1, 2])

In [41]:
X, Y = np.meshgrid(x, y)

In [42]:
X #row vector

array([[-0.1,  0. ,  0.2],
       [-0.1,  0. ,  0.2],
       [-0.1,  0. ,  0.2]])

In [43]:
Y # column vector

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

$F(X,Y) = X \times Y$

In [44]:
F = X*Y
F

array([[-0. ,  0. ,  0. ],
       [-0.1,  0. ,  0.2],
       [-0.2,  0. ,  0.4]])

# Creating Matrix: two dimensional arrays

In [49]:
np.identity(3) # square Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3, k=0) # k controls the diagonal 1 entries

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [55]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- creating a diagonal matrix with incremen entries

In [60]:
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [58]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing & Slicing

- choosing an element or a collectin of elements from an array
- similar to lists, index starts at 0.
- last index is -1, second last is -2

- one dimensional array: choosing and slicind similar to list prosedure

In [83]:
a12 = np.arange(0,6)
a12

array([0, 1, 2, 3, 4, 5])

In [86]:
print(a12[0])
print(a12[-1])

0
5


In [88]:
a12[1:3]

array([1, 2])

In [89]:
a12[3:]

array([3, 4, 5])

- matrix: two dimensional array

In [5]:
a13 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10,  11],
       [ 12,  13,  14, 15]])
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- choosing a row

In [91]:
a13[0] # first row

array([0, 1, 2, 3])

In [94]:
a13[0,:] # another way to choose first row 

array([0, 1, 2, 3])

In [104]:
a13[-1] # last row

array([12, 13, 14, 15])

In [105]:
a13[:] # choose all

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- slicing a number of rows

In [72]:
a12[1:3] # array one and two

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- choosing a column

In [95]:
a13[:,0] # another way to choose first row 

array([ 0,  4,  8, 12])

In [102]:
a13[:2,:2] # # upper left 2 x 2 submatrices

array([[0, 1],
       [4, 5]])

In [103]:
a13[2:,2:] # # lower right 2 x 2 submatrices

array([[10, 11],
       [14, 15]])

- changing a part 

In [106]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- viewing third row with a new name

In [108]:
a14 = a13[2]
a14

array([ 8,  9, 10, 11])

- giving new value for the chosen row, changes the original entries

In [113]:
a14[:]=0
a14

array([0, 0, 0, 0])

In [114]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

- copying and storing as a new array instead of changing the original array

In [116]:
a15 = a13[1].copy()
a15

array([4, 5, 6, 7])

In [118]:
a15[:] = 1
a15

array([1, 1, 1, 1])

In [119]:
a13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

- Boolean value indexed array

In [125]:
print(a13[3])

a15 = a13[3] >= 14
a15

[12 13 14 15]


array([False, False,  True,  True])

## Resizing Array

In [6]:
a13
a16 = a13.flatten()
print(a16)
print(a13)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


- reshaping with equal ammount of elements

In [15]:
print(a13.size)
a17=np.reshape(a13,(8,2))
a17

16


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [20]:
a18 = a17.transpose()
print(a18.shape)
a18

(2, 8)


array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

- adding an extra row

In [25]:
a19 = np.vstack((a18,a18[1]))
a19

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])