**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Chapter 3: Lists, Arrays, Vectors and Matrix Operations**   

**PART 1**: 

1. Types of Sequences in Python: Built-in containers

**PART 2: Previous Notebook**

2. Arrays                   
3. Column and row vector
4. Matrix representation

**PART 3**

5. Element wise operation 
6. Set operation
7. Matrix operation

**References:** 

- [NumPy](https://numpy.org/)
- Robert Johansson, Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2019, Apress).
>Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9). The source code listings can be downloaded from http://www.apress.com/9781484205549

- VanderPlas, Jacob T,  Python data science handbook: essential tools for working with data, O'Reilly Media, 2017. This book is made available [online](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) 
>The source code listings can be downloaded from [Jake's GitHub] (https://github.com/jakevdp/PythonDataScienceHandbook)

- Travis E. Oliphant(creater of NumPy), [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf)

---
**PART 3**

# Element wise operation


In [1]:
import numpy as np
np.__version__

'1.20.2'

- Element by element (elementwsie);

In [30]:
b1 = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 0,  0,  0,  0]])
print(b1)
print(b1.shape)

b2 = np.ones((3,4))
print(b2)
print(b2.shape)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


- Thus, **matrix addition** which tis carried out in elementwise form can be carried out if the shape of array is the same

In [27]:
b3 = b1 + b2
print(b3.shape)
b3

(3, 4)
(3, 4)
(3, 4)


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [1., 1., 1., 1.]])

- elementwise operation still can be **broadcasted**  if two arrays can be matched in the form of shape and size

- one dimensional **row vector** b4 is matched to two dimensional b1:

In [17]:
b4 = np.empty(4) #creating a row vector
b4.fill(2)
b4

array([2., 2., 2., 2.])

In [24]:
print(b1.shape)
print(b4.shape)

print(b1)
print(b4)

b5 = b1 + b4
b5

(3, 4)
(4,)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[2. 2. 2. 2.]


array([[2., 3., 4., 5.],
       [6., 7., 8., 9.],
       [2., 2., 2., 2.]])

-  cannot be broadcasted if size or shape not the same

In [45]:
print(np.ones(3))
b1+ np.ones(3)

[1. 1. 1.]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

- **column vector** b6 is matched to b1

In [23]:
b6 = np.array([[3],[3],[3]])
print(b6.shape)

print(b1)
print(b6)

b7 = b1 + b6
b7

(3, 1)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[[3]
 [3]
 [3]]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 3,  3,  3,  3]])

- other element wise aritmetic ooperations include: scalar multiplication, substraction, etc. 

In [34]:
print(5* b1)

[[ 0  5 10 15]
 [20 25 30 35]
 [ 0  0  0  0]]


In [37]:
print(b1/b7)

[[0.         0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667 0.7       ]
 [0.         0.         0.         0.        ]]


In [39]:
print(b1*b7)

[[ 0  4 10 18]
 [28 40 54 70]
 [ 0  0  0  0]]


- we can also array processing for a given function.
- $f(x) = cos(x)$

In [46]:
def f(x):
    return np.cos(x)

In [57]:
Xvalues = np.linspace(- np.pi, np.pi, 10)
print(Xvalues.shape)
print(Xvalues)

b8 = f(Xvalues)
print(b8)
print(b8.shape)

(10,)
[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]
[-1.         -0.76604444 -0.17364818  0.5         0.93969262  0.93969262
  0.5        -0.17364818 -0.76604444 -1.        ]
(10,)


- various builtin NumPy functions for elementwise operations

In [59]:
np.sign(b8)

array([-1., -1., -1.,  1.,  1.,  1.,  1., -1., -1., -1.])

In [60]:
np.power?

Call signature:  np.power(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'power'>
File:            /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
power(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

First array elements raised to powers from second array, element-wise.

Raise each base in `x1` to the positionally-corresponding power in
`x2`.  `x1` and `x2` must be broadcastable to the same shape. Note that an
integer type raised to a negative integer power will raise a ValueError.

Parameters
----------
x1 : array_like
    The bases.
x2 : array_like
    The exponents.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that t

- below is a special method called `vectorize` to apply for user defined function

$f(x) = \begin{cases} 
          \frac{x}{2} & x\leq 0 \\
          0 & x> 0
       \end{cases}
$


In [90]:
def f2(x):
    if x <= 0:
        return (x/2)
    else:
        return 0

In [88]:
print(Xvalues)
f2(Xvalues)

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [91]:
print(Xvalues)
f2 = np.vectorize(f2)
f2(Xvalues)

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


array([-1.57079633, -1.22173048, -0.87266463, -0.52359878, -0.17453293,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

# Vector and Matrix Operations

## Linear Equation Systems

$$
2 x_1 + 3 x_2 = 4
$$

$$
5 x_1 + 4 x_2 = 3
$$

In [97]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])
x = np.linalg.solve(A, b)
x

array([-1.,  2.])

# Towards higher dimension:

###  three dimensional array
x = np.zeros((m,n,p))

In [181]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. ve

In [180]:
x = np.array([[[1., 1.],[1., 1.],[1., 1.]]])
print(x.ndim)
print(x.shape)
x

3
(1, 3, 2)


array([[[1., 1.],
        [1., 1.],
        [1., 1.]]])

# Python for Data Analysis: [Pandas](https://pandas.pydata.org/)
Feeling adventerous? try using [Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented):
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.