**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Chapter 3: Lists, Arrays, Vectors and Matrix Operations**   

**PART 1**: 

1. Types of Sequences in Python: Built-in containers

**PART 2: Previous Notebook**

2. Arrays                   
3. Column and row vector
4. Matrix representation

**PART 3**

5. Element wise operation 
6. Set operation
7. Matrix operation

**References:** 

- [NumPy](https://numpy.org/)
- Robert Johansson, Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2019, Apress).
>Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9). The source code listings can be downloaded from http://www.apress.com/9781484205549

- VanderPlas, Jacob T,  Python data science handbook: essential tools for working with data, O'Reilly Media, 2017. This book is made available [online](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) 
>The source code listings can be downloaded from [Jake's GitHub] (https://github.com/jakevdp/PythonDataScienceHandbook)

- Travis E. Oliphant(creater of NumPy), [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf)

---
**PART 3**

# Elementwise operation


In [160]:
import numpy as np
np.__version__

'1.20.2'

- Element by element (elementwsie);

In [161]:
b1 = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 0,  0,  0,  0]])
print(b1)
print(b1.shape)

b2 = np.ones((3,4))
print(b2)
print(b2.shape)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


- Thus, **matrix addition** which tis carried out in elementwise form can be carried out if the shape of array is the same

In [162]:
b3 = b1 + b2
print(b3.shape)
b3

(3, 4)


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [1., 1., 1., 1.]])

- elementwise operation still can be **broadcasted**  if two arrays can be matched in the form of shape and size

- one dimensional **row array** b4 is matched to two dimensional b1:

In [163]:
b4 = np.empty(4) #creating a row vector
b4.fill(2)
b4

array([2., 2., 2., 2.])

In [164]:
print(b1.shape)
print(b4.shape)

print(b1)
print(b4)

b5 = b1 + b4
b5

(3, 4)
(4,)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[2. 2. 2. 2.]


array([[2., 3., 4., 5.],
       [6., 7., 8., 9.],
       [2., 2., 2., 2.]])

-  cannot be broadcasted if size or shape not the same

In [165]:
print(np.ones(3))
b1+ np.ones(3)

[1. 1. 1.]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

- **column array** b6 is matched to b1

In [166]:
b6 = np.array([[3],[3],[3]])
print(b6.shape)

print(b1)
print(b6)

b7 = b1 + b6
b7

(3, 1)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[[3]
 [3]
 [3]]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 3,  3,  3,  3]])

- other element wise aritmetic ooperations include: scalar multiplication, substraction, etc. 

In [167]:
print(5* b1)

[[ 0  5 10 15]
 [20 25 30 35]
 [ 0  0  0  0]]


In [168]:
print(b1/b7)

[[0.         0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667 0.7       ]
 [0.         0.         0.         0.        ]]


In [169]:
print(b1*b7)

[[ 0  4 10 18]
 [28 40 54 70]
 [ 0  0  0  0]]


In [171]:
b7 = np.ceil(np.random.normal(0, 3, size = 6)) 
print(b7)
np.sign(b7)

[-4.  9. -1.  1. -1. -2.]


array([-1.,  1., -1.,  1., -1., -1.])

In [172]:
np.power(b7,3)

array([-64., 729.,  -1.,   1.,  -1.,  -8.])

### User Defined Function for array processing

In [173]:
np.cos(np.pi)

-1.0

- we can also array processing for a given function.
- $f1(x) = cos(x)$

In [174]:
def f1(x):
    return np.cos(x)

In [175]:
Xvalues = np.linspace(- np.pi, np.pi, 10)
print(Xvalues.shape)
print(Xvalues)

b8 = f1(Xvalues)
print(b8)
print(b8.shape)

(10,)
[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]
[-1.         -0.76604444 -0.17364818  0.5         0.93969262  0.93969262
  0.5        -0.17364818 -0.76604444 -1.        ]
(10,)


- various builtin NumPy functions for elementwise operations

- below is a special method called `vectorize` to apply for user defined function

$f(x) = \begin{cases} 
          \frac{x}{2} & x\leq 0 \\
          0 & x> 0
       \end{cases}
$


In [176]:
def f3(x):
    if x <= 0:
        return (x/2)
    else:
        return 0

In [177]:
print(Xvalues)
b9 = f3(Xvalues)

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [178]:
print(b8)
f3 = np.vectorize(f3)
b9 = f3(Xvalues)

[-1.         -0.76604444 -0.17364818  0.5         0.93969262  0.93969262
  0.5        -0.17364818 -0.76604444 -1.        ]


### Functions takes in array and returns a scalar

In [179]:
print(b9)
print(b9.sum())
print(b9.prod())


[-1.57079633 -1.22173048 -0.87266463 -0.52359878 -0.17453293  0.
  0.          0.          0.          0.        ]
-4.363323129985824
-0.0


-  descriptive statistics

In [180]:
print(np.mean(b9))
print(b9.min())
print(b9.max())
print(b9.mean())
print(b9.std())
print(b9.var())

-0.43633231299858244
-1.5707963267948966
0.0
-0.43633231299858244
0.5587780017872718
0.31223285528137634


- operation on arrays

In [181]:
print(b1)
b1new=b1.transpose()
print(b1new)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[[0 4 0]
 [1 5 0]
 [2 6 0]
 [3 7 0]]


In [182]:
print(b1new.sort(1))
b1new

None


array([[0, 0, 4],
       [0, 1, 5],
       [0, 2, 6],
       [0, 3, 7]])

### Conditional Expression on arrays

In [183]:
b10 =  np.random.normal(size = (5))
b11 =  np.random.normal(size = (5))
print(b10)
print(b11)

[-0.19548739 -1.07755833  1.23661305  0.44680951 -0.15685945]
[-1.77056144 -1.39914671 -0.8358154  -0.71171863 -0.90599595]


In [184]:
b10 > b11

array([ True,  True,  True,  True,  True])

In [185]:
np.all( b10 > -2) #all elements must satisfy condition to be True

True

In [186]:
np.any( b10 > 1)  #any element may satisfy condition to be True

True

In [187]:
np.all(b10 > b11)

True

In [188]:
#if the element satisfy given condition, then make it a positive number, else keep it as it is
print(b10)
np.where( b10 < 0, abs(b10), b10 )

[-0.19548739 -1.07755833  1.23661305  0.44680951 -0.15685945]


array([0.19548739, 1.07755833, 1.23661305, 0.44680951, 0.15685945])

### Set Like operations

In [189]:
b11 = np.ceil(np.random.normal(10, 3, size = 6)) # an array of rand nu centered at 10, with spread of 5, size of 6
b12 = np.ceil(np.random.normal(10, 3, size = 6)) 
print(b11)
print(b12)

[ 7. 19. 13.  9. 13.  6.]
[10. 10. 11.  8. 14.  9.]


In [190]:
print(np.unique(b11))
print(np.unique(b12))
print(np.in1d(b11,b12)) # check in order if the elements in b11 is in b12
print(np.intersect1d(b11,b12))
print(np.union1d(b11,b12))

[ 6.  7.  9. 13. 19.]
[ 8.  9. 10. 11. 14.]
[False False False  True False False]
[9.]
[ 6.  7.  8.  9. 10. 11. 13. 14. 19.]


In [191]:
5 in b11

False

In [192]:
12 in b11

False

# Vector and Matrix Operations

### NumPy standard matrix operation

In [193]:
m1 = np.arange(1,7).reshape(2,3)
print(m1)
m2 = np.arange(7,13).reshape(3,2)
print(m2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


- inner product

In [194]:
np.inner(m1,3) # elementwise scalar multiplication

array([[ 3,  6,  9],
       [12, 15, 18]])

- dor product

In [195]:
print(m1.shape)
print(m2.shape)
np.dot(m1,m2)

(2, 3)
(3, 2)


array([[ 58,  64],
       [139, 154]])

- cross product

In [196]:
m3 = np.arange(14,20).reshape(2,3)
print(m3)
np.cross(m1,m3)

[[14 15 16]
 [17 18 19]]


array([[-13,  26, -13],
       [-13,  26, -13]])

-  vector (inner product)

In [197]:
v1 = np.arange(1,4)
v2 =np.arange(4,7)
print(v1,v2)
print(np.inner(v1,v2)) # must in the same dimension
print(np.vdot(v1,v2)) # can be either in a row or column vector 

[1 2 3] [4 5 6]
32
32


- vector `outer product` maps two vectors into a matrix:

> first row: 1*[4 5 6]

> second row: 2*[4 5 6]

> third row: 3*[4 5 6]

In [198]:
print(np.outer(v1,v2)) # can be either in a row or column vector 

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Linear Algebra functions:
read the documentation [online](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [199]:
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from 'C:\\Users\\Apple\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\linalg\\__init__.py'>
File:        c:\users\apple\appdata\roaming\python\python38\site-packages\numpy\linalg\__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpo

### Linear Equation Systems

$$
2 x_1 + 3 x_2 = 4
$$

$$
5 x_1 + 4 x_2 = 3
$$

In [200]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])
x = np.linalg.solve(A, b)
x

array([-1.,  2.])

In [201]:
print(np.linalg.det(A))
print(np.linalg.eigvals(A))
print(np.linalg.norm(A))
print(np.linalg.inv(A))

-6.999999999999999
[-1.  7.]
7.3484692283495345
[[-0.57142857  0.42857143]
 [ 0.71428571 -0.28571429]]


# Towards higher dimensions:

###  three dimensional array: Imagine layered cake!

<img src="figures/layeredCake.jpg" alt="Drawing" style="width: 200px;"/>

- example of 2 depths or tables overlaid, with 3 rows and 4 columns each table.

In [202]:
h1=np.arange(1,25).reshape(2,3,4) 
print(h1.ndim)
print(h1.shape)
h1

3
(2, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

- layer 1: first table

In [203]:
h1[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-layer 2: second table

In [204]:
h2[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

# Python for Data Analysis: [Pandas](https://pandas.pydata.org/)
Feeling adventerous? try using [Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented):
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.