**Scientific Computation (MKP3303)**


> R.U.Gobithaasan (2021). Scientific Computing, Lectures for Undergraduate Degree Program B.Sc (Applied Mathematics), Faculty of Ocean Engineering Technology & Informatics, University Malaysia Terengganu.
https://sites.google.com/site/gobithaasan/LearnTeach

<p align="center">
     © 2021 R.U. Gobithaasan All Rights Reserved.

</p>



**Chapter 3: Lists, Arrays, Vectors and Matrix Operations**   

**PART 1**: 

1. Types of Sequences in Python: Built-in containers

**PART 2: Previous Notebook**

2. Arrays                   
3. Column and row vector
4. Matrix representation

**PART 3**

5. Element wise operation 
6. Set operation
7. Matrix operation

**References:** 

- [NumPy](https://numpy.org/)
- Robert Johansson, Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2019, Apress).
>Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9). The source code listings can be downloaded from http://www.apress.com/9781484205549

- VanderPlas, Jacob T,  Python data science handbook: essential tools for working with data, O'Reilly Media, 2017. This book is made available [online](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) 
>The source code listings can be downloaded from [Jake's GitHub] (https://github.com/jakevdp/PythonDataScienceHandbook)

- Travis E. Oliphant(creater of NumPy), [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf)

---
**PART 3**

# Elementwise operation


In [1]:
import numpy as np
np.__version__

'1.20.2'

- Element by element (elementwsie);

In [2]:
b1 = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 0,  0,  0,  0]])
print(b1)
print(b1.shape)

b2 = np.ones((3,4))
print(b2)
print(b2.shape)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


- Thus, **matrix addition** which tis carried out in elementwise form can be carried out if the shape of array is the same

In [3]:
b3 = b1 + b2
print(b3.shape)
b3

(3, 4)


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [1., 1., 1., 1.]])

- elementwise operation still can be **broadcasted**  if two arrays can be matched in the form of shape and size

- one dimensional **row array** b4 is matched to two dimensional b1:

In [4]:
b4 = np.empty(4) #creating a row vector
b4.fill(2)
b4
b4.shape

(4,)

In [5]:
print(b1.shape)
print(b4.shape)

print(b1)
print(b4)

b5 = b1 + b4
b5

(3, 4)
(4,)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[2. 2. 2. 2.]


array([[2., 3., 4., 5.],
       [6., 7., 8., 9.],
       [2., 2., 2., 2.]])

-  cannot be broadcasted if size or shape not the same

In [6]:
print(np.ones(3))
# b1 + np.ones(3) # you will not be able to run this due to unmatached dimension

[1. 1. 1.]


- **column array** b6 is matched to b1

In [7]:
b6 = np.array([[3],[3],[3]])
print(b6)
print(b6.shape)

print(b1)
print(b6)

b7 = b1 + b6
b7

[[3]
 [3]
 [3]]
(3, 1)
[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[[3]
 [3]
 [3]]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 3,  3,  3,  3]])

- other element wise aritmetic ooperations include: scalar multiplication, substraction, etc. 

In [8]:
print(5* b1)

[[ 0  5 10 15]
 [20 25 30 35]
 [ 0  0  0  0]]


In [9]:
print(b1)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]


In [10]:
print(b7)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [ 3  3  3  3]]


In [11]:
print(b1/b7)

[[0.         0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667 0.7       ]
 [0.         0.         0.         0.        ]]


In [12]:
print(b1*b7)

[[ 0  4 10 18]
 [28 40 54 70]
 [ 0  0  0  0]]


In [13]:
a1 = np.random.normal(0, 3, size = 6)
a1

array([ 1.35910511,  3.88004197, -2.00229281, -0.46805341,  0.64890429,
        2.03694384])

In [14]:
b7 = np.ceil(a1) 
print(b7)
np.sign(b7)

[ 2.  4. -2. -0.  1.  3.]


array([ 1.,  1., -1.,  0.,  1.,  1.])

In [15]:
np.power(b7,3)

array([ 8., 64., -8., -0.,  1., 27.])

### User Defined Function for array processing

In [16]:
np.cos(np.pi)

-1.0

- we can also array processing for a given function.
- $f1(x) = cos(x)$

In [17]:
def f1(x):
    return np.cos(x)

In [18]:
Xvalues = np.linspace(- np.pi, np.pi, 10)
print(Xvalues.shape)
print(Xvalues)

b8 = f1(Xvalues)
print(b8)
print(b8.shape)

(10,)
[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]
[-1.         -0.76604444 -0.17364818  0.5         0.93969262  0.93969262
  0.5        -0.17364818 -0.76604444 -1.        ]
(10,)


- various builtin NumPy functions for elementwise operations

- below is a special method called `vectorize` to apply for user defined function

$f(x) = \begin{cases} 
          \frac{x}{2} & x\leq 0 \\
          0 & x> 0
       \end{cases}
$


In [19]:
def f3(x):
    if x <= 0:
        return (x/2)
    else:
        return 0

In [20]:
f3(2)

0

In [21]:
print(Xvalues)
# b9 = f3(Xvalues) # you will not be able to run this since this fucntion does not take in raay as input

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


In [22]:
print(b8)
f3 = np.vectorize(f3)
b9 = f3(Xvalues)

[-1.         -0.76604444 -0.17364818  0.5         0.93969262  0.93969262
  0.5        -0.17364818 -0.76604444 -1.        ]


### Functions takes in array and returns a scalar

In [23]:
print(b9)
print(b9.sum())
print(b9.prod())

[-1.57079633 -1.22173048 -0.87266463 -0.52359878 -0.17453293  0.
  0.          0.          0.          0.        ]
-4.363323129985824
-0.0


-  descriptive statistics

In [24]:
print(np.mean(b9))
print(b9.min())
print(b9.max())
print(b9.mean())
print(b9.std())
print(b9.var())

-0.43633231299858244
-1.5707963267948966
0.0
-0.43633231299858244
0.5587780017872718
0.31223285528137634


- operation on arrays

In [25]:
print(b1)
b1new=b1.transpose()
print(b1new)

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]
[[0 4 0]
 [1 5 0]
 [2 6 0]
 [3 7 0]]


In [26]:
print(b1new.sort(1))
b1new

None


array([[0, 0, 4],
       [0, 1, 5],
       [0, 2, 6],
       [0, 3, 7]])

### Conditional Expression on arrays

In [27]:
b10 =  np.random.normal(size = (5))
b11 =  np.random.normal(size = (5))
print(b10)
print(b11)

[ 0.02501342 -1.0694752   2.25783345 -0.0572897  -1.08028832]
[ 1.1769562  -1.2315709  -1.01749091  0.13621551  1.99172295]


In [28]:
b10 > b11

array([False,  True,  True, False, False])

In [29]:
np.all( b10 > -2) #all elements must satisfy condition to be True

True

In [30]:
np.any( b10 > 1)  #any element may satisfy condition to be True

True

In [31]:
np.all(b10 > b11)

False

In [32]:
#if the element satisfy given condition, then make it a positive number, else keep it as it is
print(b11)
np.where( b11 < 0, abs(b11), 0 )

[ 1.1769562  -1.2315709  -1.01749091  0.13621551  1.99172295]


array([0.        , 1.2315709 , 1.01749091, 0.        , 0.        ])

### Set Like operations

In [33]:
b11 = np.ceil(np.random.normal(10, 3, size = 6)) # an array of rand nu centered at 10, with spread of 5, size of 6
b12 = np.ceil(np.random.normal(10, 3, size = 6)) 
print(b11)
print(b12)

[13. 11. 12. 10. 17.  8.]
[ 9.  6. 10.  9. 14. 18.]


In [34]:
print(np.unique(b11))
print(np.unique(b12))
print(np.in1d(b11,b12)) # check in order if the elements in b11 is in b12
print(np.intersect1d(b11,b12))
print(np.union1d(b11,b12))

[ 8. 10. 11. 12. 13. 17.]
[ 6.  9. 10. 14. 18.]
[False False False  True False False]
[10.]
[ 6.  8.  9. 10. 11. 12. 13. 14. 17. 18.]


In [35]:
5 in b11

False

In [36]:
12 in b11

True

# Vector and Matrix Operations

### NumPy standard matrix operation

In [37]:
m1 = np.arange(1,7).reshape(2,3)
print(m1)
m2 = np.arange(7,13).reshape(3,2)
print(m2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


- inner product

In [38]:
np.inner(m1,3) # elementwise scalar multiplication

array([[ 3,  6,  9],
       [12, 15, 18]])

- dor product

In [39]:
print(m1.shape)
print(m2.shape)
np.dot(m1,m2)

(2, 3)
(3, 2)


array([[ 58,  64],
       [139, 154]])

- cross product

In [40]:
m3 = np.arange(14,20).reshape(2,3)
print(m3)
np.cross(m1,m3)

[[14 15 16]
 [17 18 19]]


array([[-13,  26, -13],
       [-13,  26, -13]])

-  vector (inner product)

In [41]:
v1 = np.arange(1,4)
v2 =np.arange(4,7)
print(v1,v2)
print(np.inner(v1,v2)) # must in the same dimension
print(np.vdot(v1,v2)) # can be either in a row or column vector 

[1 2 3] [4 5 6]
32
32


- vector `outer product` maps two vectors into a matrix:

> first row: 1*[4 5 6]

> second row: 2*[4 5 6]

> third row: 3*[4 5 6]

In [42]:
print(np.outer(v1,v2)) # can be either in a row or column vector 

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Linear Algebra functions:
read the documentation [online](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [43]:
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from 'C:\\Users\\Apple\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\linalg\\__init__.py'>
File:        c:\users\apple\appdata\roaming\python\python38\site-packages\numpy\linalg\__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpo

### Linear Equation Systems

$$
2 x_1 + 3 x_2 = 4
$$

$$
5 x_1 + 4 x_2 = 3
$$

In [44]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])
x = np.linalg.solve(A, b)
x

array([-1.,  2.])

In [45]:
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.linalg.eigvals(A))
print(np.linalg.norm(A))


-6.999999999999999
[[-0.57142857  0.42857143]
 [ 0.71428571 -0.28571429]]
[-1.  7.]
7.3484692283495345


# Towards higher dimensions:

###  three dimensional array: Imagine layered cake!

<img src="figures/layeredCake.jpg" alt="Drawing" style="width: 200px;"/>

- example of 2 depths or tables overlaid, with 3 rows and 4 columns each table.

In [46]:
h1=np.arange(1,25).reshape(2,3,4) 
print(h1.ndim)
print(h1.shape)
h1

3
(2, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

- layer 1: first table

In [47]:
h1[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-layer 2: second table

In [48]:
h1[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

# Reading & Writing files
- **A comma-separated values (CSV) file** is a delimited text file that uses a comma to separate values.\
- Each line of the file is a data record. 
- Each record consists of one or more fields, separated by commas. 
- The use of the comma as a field separator is the source of the name for this file format. 
- A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields.

Feeling adventerous? try using [Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented):
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

### Writing an array into csv file

Let's see a simple example of generating 50 rows and 5 columns of data. 

In [49]:
dataset = np.arange(1,101).reshape(20,5)
dataset

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

-  We use the `np.loadtxt` function. 
- saving the array above in a folder called `data` and the file is named as `dataset.csv`.
- the format `fmt = %.2f` means to two significant digits
- each entry is separated by comma
- the `header` is a string of five columns

You may open the folder and click on the file to view in MS Excel.

In [50]:
np.savetxt('data/dataset.csv', dataset, fmt = '%.2f', delimiter=',', header = 'X1, X2, X3, X4, X5')

### Reading a csv file
- using the `np.loadtxt` function. 
- there is a file in the folder called `data` named `populations.csv`. The data describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years:

In [51]:
samples = np.loadtxt('data/populations.csv', delimiter=',')
! head -n 6 'data/populations.txt'

# year	hare	lynx	carrot
1900	30e3	4e3	48300
1901	47.2e3	6.1e3	48200
1902	70.2e3	9.8e3	41500
1903	77.4e3	35.2e3	38200
1904	36.3e3	59.4e3	40600


In [52]:
print(samples)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [53]:
year, hare, lynxe, carrot = samples.T  # trick: columns to variables

In [54]:
hare

array([30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
       22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
       11200.,  7600., 14600., 16200., 24700.])

# Bonus: Python for Data Analysis (Pandas)
Feeling adventerous? try using [Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented):
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

In [55]:
#!pip install pandas

In [56]:
import pandas as pd
pd.__version__

'1.2.4'

In [57]:
populations = pd.read_csv("data/populations.csv")
type(populations)

pandas.core.frame.DataFrame

In [58]:
populations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   # year  21 non-null     int64  
 1   hare    21 non-null     float64
 2   lynx    21 non-null     float64
 3   carrot  21 non-null     int64  
dtypes: float64(2), int64(2)
memory usage: 800.0 bytes


In [59]:
populations.head(5)

# year     hare     lynx  carrot
0    1900  30000.0   4000.0   48300
1    1901  47200.0   6100.0   48200
2    1902  70200.0   9800.0   41500
3    1903  77400.0  35200.0   38200
4    1904  36300.0  59400.0   40600

In [60]:
populations["hare"].mean()

34080.95238095238

In [61]:
populations.describe()

# year          hare          lynx        carrot
count    21.000000     21.000000     21.000000     21.000000
mean   1910.000000  34080.952381  20166.666667  42400.000000
std       6.204837  21413.981859  16655.999920   3404.555771
min    1900.000000   7600.000000   4000.000000  36700.000000
25%    1905.000000  19500.000000   8600.000000  39800.000000
50%    1910.000000  25400.000000  12300.000000  41800.000000
75%    1915.000000  47200.000000  29700.000000  44500.000000
max    1920.000000  77400.000000  59400.000000  48300.000000